In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlin inline

UsageError: Line magic function `%matplotlin` not found.


In [3]:
df=pd.read_csv('Social_Network_Ads.csv')

In [4]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [8]:
df.drop('User ID',axis=1,inplace=True)

In [9]:
df

Gender  Age  EstimatedSalary  Purchased
0      Male   19            19000          0
1      Male   35            20000          0
2    Female   26            43000          0
3    Female   27            57000          0
4      Male   19            76000          0
..      ...  ...              ...        ...
395  Female   46            41000          1
396    Male   51            23000          1
397  Female   50            20000          1
398    Male   36            33000          0
399  Female   49            36000          1

[400 rows x 4 columns]

In [10]:
df.Gender=pd.get_dummies(df.Gender,drop_first=True)

In [11]:
df

Gender  Age  EstimatedSalary  Purchased
0         1   19            19000          0
1         1   35            20000          0
2         0   26            43000          0
3         0   27            57000          0
4         1   19            76000          0
..      ...  ...              ...        ...
395       0   46            41000          1
396       1   51            23000          1
397       0   50            20000          1
398       1   36            33000          0
399       0   49            36000          1

[400 rows x 4 columns]

In [13]:
X=df.drop('Purchased',axis=1)
y=df.Purchased

In [14]:
X

Gender  Age  EstimatedSalary
0         1   19            19000
1         1   35            20000
2         0   26            43000
3         0   27            57000
4         1   19            76000
..      ...  ...              ...
395       0   46            41000
396       1   51            23000
397       0   50            20000
398       1   36            33000
399       0   49            36000

[400 rows x 3 columns]

In [15]:
y

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int64

In [36]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=10)

# LOGISTIC REGRESSION

In [37]:
from sklearn.linear_model import LogisticRegression
log=LogisticRegression()
log.fit(X_train,y_train)

LogisticRegression()

In [38]:
log.score(X_train,y_train)*100

64.0625

In [39]:
log.score(X_test,y_test)*100

65.0

The accuracy score is quite low. 65% it will predict accurately.

In [42]:
df.head()

Gender  Age  EstimatedSalary  Purchased
0       1   19            19000          0
1       1   35            20000          0
2       0   26            43000          0
3       0   27            57000          0
4       1   19            76000          0

In [41]:
log.predict([(1,19,19000)])

array([0])

Correctly predicted

In [43]:
log.predict([(1,35,20000)])

array([0])

In [67]:
log.predict([(1,51,23000)])

array([0])

Incorrectly Predicted

# DECISION TREE

In [63]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=20)
dt.fit(X_train,y_train)

DecisionTreeClassifier(random_state=20)

In [64]:
dt.score(X_train,y_train)

0.996875

In [65]:
dt.score(X_test,y_test)

0.9

The accuracy score with decision Tree is very good.

In [66]:
dt.predict([(1,51,23000)])

array([1])

The sample wich as incorrectly peredicted in Logisitic Regression is correctly predicted by Decision Tree